# Generated by Django 5.0.2 on 2024-03-03 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('tipo', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('cedula', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=13)),
                ('numero', models.IntegerField()),
                ('contrato_codigo', models.CharField(max_length=30)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ciudad')),
                ('tipo_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to='usuarios.tipopersona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('cedula', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=13)),
                ('id', models.IntegerField(unique=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ciudad')),
                ('tipo_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='usuarios.tipopersona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
