# Generated by Django 5.0.1 on 2024-03-07 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1024)),
                ('fecha_solicitud', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoContable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudContable',
            fields=[
                ('solicitud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solicitud.solicitud')),
                ('presupuesto', models.FloatField()),
                ('cuenta_cobro', models.CharField(max_length=10)),
                ('tipo_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.tipocontable')),
            ],
            bases=('solicitud.solicitud',),
        ),
        migrations.CreateModel(
            name='SolicitudEspacio',
            fields=[
                ('solicitud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solicitud.solicitud')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.espacio')),
            ],
            bases=('solicitud.solicitud',),
        ),
    ]
