# Generated by Django 4.2.11 on 2024-04-28 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('usuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PropositoViaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proposito', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1024)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudClases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.clase')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudViatico',
            fields=[
                ('solicitud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solicitud.solicitud')),
                ('fecha_ida', models.DateField(blank=True, null=True)),
                ('fecha_vuelta', models.DateTimeField(blank=True, null=True)),
                ('tiquete', models.BooleanField()),
                ('hospedaje', models.BooleanField()),
                ('alimentacion', models.BooleanField()),
                ('clase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.clase')),
                ('propositoViaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitud.propositoviaje')),
            ],
            bases=('solicitud.solicitud',),
        ),
        migrations.CreateModel(
            name='SolicitudEspacio',
            fields=[
                ('solicitud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solicitud.solicitud')),
                ('clases', models.ManyToManyField(through='solicitud.SolicitudClases', to='academico.clase')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitud.estadosolicitud')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            bases=('solicitud.solicitud',),
        ),
        migrations.AddField(
            model_name='solicitudclases',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.solicitudespacio'),
        ),
    ]
