# Generated by Django 5.0.3 on 2024-04-12 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropositoViaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proposito', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudViatico',
            fields=[
                ('solicitud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solicitud.solicitud')),
                ('fecha_ida', models.DateField()),
                ('fecha_vuelta', models.DateTimeField()),
                ('tiquete', models.BooleanField()),
                ('hospedaje', models.BooleanField()),
                ('alimentacion', models.BooleanField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.docente')),
                ('propositoViaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.propositoviaje')),
            ],
            bases=('solicitud.solicitud',),
        ),
    ]
