# Generated by Django 4.2.11 on 2024-04-28 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nrc', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.IntegerField()),
                ('cupo', models.IntegerField()),
                ('intu_generado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.persona')),
                ('codigo', models.CharField(max_length=30, unique=True)),
            ],
            bases=('usuarios.persona',),
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoDeClase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entrega_notas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metodologia', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('semestre', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeMateria',
            fields=[
                ('tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDePrograma',
            fields=[
                ('tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.director')),
                ('estado_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estadosolicitud')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.facultad')),
                ('tipo_de_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.tipodeprograma')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('creditos', models.IntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.departamento')),
                ('programas', models.ManyToManyField(through='academico.MallaCurricular', to='academico.programa')),
                ('tipo_de_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.tipodemateria')),
            ],
        ),
        migrations.AddField(
            model_name='mallacurricular',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.materia'),
        ),
        migrations.AddField(
            model_name='mallacurricular',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodo'),
        ),
        migrations.AddField(
            model_name='mallacurricular',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.programa'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante', to_field='codigo')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(through='academico.Inscripcion', to='academico.curso'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='periodo_inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodo'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.programa'),
        ),
        migrations.CreateModel(
            name='EspacioClase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edificio', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.espacio')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.materia'),
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academico.periodo'),
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_fin', models.DateTimeField(null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.docente')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.espacio')),
                ('espacio_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.espacioclase')),
                ('grupo_clases', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.grupodeclase')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.modalidad')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mallacurricular',
            constraint=models.UniqueConstraint(fields=('materia', 'programa', 'periodo'), name='unique_materia_programa_periodo'),
        ),
        migrations.AlterUniqueTogether(
            name='espacioclase',
            unique_together={('edificio', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('grupo', 'materia', 'periodo')},
        ),
    ]
