# Generated by Django 5.0.2 on 2024-03-03 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('metodologia', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('semestre', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeMateria',
            fields=[
                ('tipo', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='facultad',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipodeprograma',
            name='tipo',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('creditos', models.IntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.departamento')),
                ('tipo_de_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.tipodemateria')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nrc', models.IntegerField(primary_key=True, serialize=False)),
                ('grupo', models.IntegerField()),
                ('cupo', models.IntegerField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_fin', models.DateTimeField(null=True)),
                ('espacio_asignado', models.CharField(max_length=255, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.espacio')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.modalidad')),
            ],
        ),
    ]
