# Generated by Django 5.0.3 on 2024-03-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_clase_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='espacio_asignado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
