# Generated by Django 5.0.3 on 2024-04-12 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_clase_espacio_asignado'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='espacio_asignado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.persona')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('periodo_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodo')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.programa')),
            ],
            bases=('usuarios.persona',),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante', to_field='codigo')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(through='academico.Inscripcion', to='academico.curso'),
        ),
    ]
