# Generated by Django 4.2.11 on 2024-04-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_alter_clase_espacio_asignado_estudiante_inscripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoDeClase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entrega_notas', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='intu_generado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EspacioClase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edificio', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.espacio')),
            ],
            options={
                'unique_together': {('edificio', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='grupo_clases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.grupodeclase'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='espacio_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.espacioclase'),
        ),
    ]
