# Exported from Render on 2024-04-23T03:03:17Z
services:
- type: web
  name: ccsa-programacion-academica
  runtime: python
  repo: https://github.com/ICESI-PI1-2024A-G1/proyecto-t3
  branch: deploy
  plan: free
  envVars:
  - key: SECRET_KEY
    sync: false
  - key: DEBUG
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: ALLOWED_HOSTS
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn ccsa_project.wsgi
  rootDir: src
version: "1"